updates

diff --git a/.github/actions/build-nodejs/action.yml b/.github/actions/build-nodejs/action.yml
--- a/.github/actions/build-nodejs/action.yml
+++ b/.github/actions/build-nodejs/action.yml
@@ -40,50 +40,55 @@ runs:
         id: cache
         uses: actions/cache@v3
         with:
-          path: node_modules
+          path: ${{ inputs.app-base-dir }}/node_modules
           key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}
 
       - name: Install Dependencies
         id: install
         if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
         run: |
+          cd ${{ inputs.app-base-dir }}
           yarn install
           echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
         shell: bash
 
       - name: Build Code
         run: |
+          cd ${{ inputs.app-base-dir }}
           yarn run build
         shell: bash
 
       - name: Lint Code
         run: |
+          cd ${{ inputs.app-base-dir }}
           yarn run lint
         shell: bash
 
       - name: Test Code
         run: |
+          cd ${{ inputs.app-base-dir }}
           yarn run test
         shell: bash
 
-      - name: Test BDD Code
-        if: inputs.run-bdd-test == 'true'
-        run: |
-          yarn run e2e
-        shell: bash
+      # - name: Test BDD Code
+      #   if: inputs.run-bdd-test == 'true'
+      #   run: |
+      #     cd ${{ inputs.app-base-dir }}
+      #     yarn run e2e
+      #   shell: bash
           
-      - name: Generate Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: JEST Tests
-          path: reports/jest-*.xml
-          reporter: jest-junit
+      # - name: Generate Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()    # run this step even if previous step failed
+      #   with:
+      #     name: JEST Tests
+      #     path: ${{ inputs.app-base-dir }}/reports/jest-*.xml
+      #     reporter: jest-junit
 
-      - name: Upload Test Results
-        uses: actions/upload-artifact@v3
-        if: always() 
-        with:
-          name: Upload Test Results
-          path: |
-            reports/jest-*.xml
+      # - name: Upload Test Results
+      #   uses: actions/upload-artifact@v3
+      #   if: always() 
+      #   with:
+      #     name: Upload Test Results
+      #     path: |
+      #       ${{ inputs.app-base-dir }}/reports/jest-*.xml
